# nginx reverse-proxy
nginx:
  build: install/docker/nginx/
  ports:
    - "80:80"
  volumes_from:
    - dataprobr
  links:
    - web:probr_core

# probr-core, django app
web:
   build: .
   command: sh install/docker/web/run.sh
   ports:
     - "8001:8001"
     - "8002:8002"
   volumes_from:
     - dataprobr
   links:
     - postgres:postgres
     - redis:redis


# probr-core, websockets
worker:
   build: .
   command: sh install/docker/web/worker.sh
   volumes_from:
     - dataprobr
   links:
     - postgres:postgres
     - redis:redis

# database container
postgres:
   image: postgres:9.4.5
   environment:
     POSTGRES_USER: probr
     POSTGRES_PASSWORD: probr

# redis container
redis:
   image: redis:2.8.19

# data container for probr
dataprobr:
  image: cogniteev/echo
  volumes:
    - ./media:/app/media
    - ./static:/app/static